pre-release (0.7.0-beta1) housekeeping

diff --git a/scripts/new/app b/scripts/new/app
--- a/scripts/new/app
+++ b/scripts/new/app
@@ -16,17 +16,21 @@ fi
 if [ -a $FIO_APPNAME ]; then echo "Couldn't create folder, already exists?"; exit 1; fi
 if [ -d $FIO_APPNAME ]; then echo "Couldn't create folder, already exists?"; exit 1; fi
 
+if [[ ! -z "${FIO_BRANCH}" ]]; then
+  FIO_URL=https://github.com/boazsegev/facil.io/archive/${FIO_BRANCH}.tar.gz
+elif [[ ! -z "${FIO_RELEASE}" ]]; then
+  FIO_URL=$(curl -s https://api.github.com/repos/boazsegev/facil.io/releases/tags/${FIO_RELEASE} | grep tarball_url | cut -d '"' -f 4)
+else
+  FIO_URL=$(curl -s https://api.github.com/repos/boazsegev/facil.io/releases/latest | grep tarball_url | cut -d '"' -f 4)
+fi
+
+if [[ -z "${FIO_URL}" ]]; then echo "URL error, FIO_BRANCH or FIO_RELEASE don't exist?"; exit 1; fi
+
 echo "* Creating $FIO_APPNAME"
 mkdir $FIO_APPNAME
 cd $FIO_APPNAME
 
-if [[ -z "${FIO_BRANCH}" ]]; then
-  FIO_URL=$(curl -s https://api.github.com/repos/boazsegev/facil.io/releases/latest | grep tarball_url | cut -d '"' -f 4)
-else
-  FIO_URL=https://github.com/boazsegev/facil.io/archive/${FIO_BRANCH}.tar.gz
-fi
-
-echo $FIO_URL
+echo "* Downloading from $FIO_URL"
 
 # Was: curl -s -LJO https://github.com/boazsegev/facil.io/archive/stable.tar.gz
 # But it's better to use releases than the stable branch:
@@ -39,4 +43,5 @@ if [ $? -ne 0 ]; then echo "Couldn't extract tar."; exit 1; fi
 
 rm facil.io.tar.gz
 
+echo "* Cleaning up and placing example code."
 ./scripts/new/cleanup
